[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[profile.default.networks]
celo-alfajores = { url = "https://alfajores-forno.celo-testnet.org", chain_id = 44787 }

[etherscan]
celo-alfajores = { key = "${CELOSCAN_API_KEY}", url = "https://api-alfajores.celoscan.io/api", chain = 44787 }

